### ISSUE TITLE
Secured application API throws error 500, when Bearer token send as blank

### ISSUE THREAD

**Issue by sivadas** [predix/spring-jwt-validation-filter#54]
API returns error 500, if the Authorization token send as "Bearer ". Below is API response and log from server.
{
    "timestamp": 1528216494396,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.NullPointerException",
    "message": "",
    "path": "......."
}

java.lang.NullPointerException 
at com.ge.predix.uaa.token.lib.FastTokenServices.getIssuerFromClaims(FastTokenServices.java:359)
at com.ge.predix.uaa.token.lib.FastTokenServices.loadAuthentication(FastTokenServices.java:127)

It should throw error 401 incase of blank or invalid tokens.

**Comment by irinaepshteyn** [comment]
@sivadas, the issue has been fixed with release 4.0.1
https://mvnrepository.com/artifact/com.ge.predix/uaa-token-lib/4.0.1

Returning 401 Unauthorized in case of malformed or blank token.
